### ISSUE TITLE
ls -> Error: password store is empty... (1)

### ISSUE THREAD

**Issue by tvo6** [passff/passff-host#19]
Hello,

I'm not sure if it's a passff-host or passff issue but here are the details:

### General information. Describe your environment

- Versions
  - Operating system:  Debian GNU/Linux unstable (sid)
  - Browser: firefox 60.0.1-5 (and firefox-l10n-fr 60.0.1-5) (debian package)
  - pass: v1.7.1 (debian package 1.7.1-4)
  - PassFF: 1.3 (from mozilla website: https://addons.mozilla.org/fr/firefox/addon/passff/)
  - Host app: 1.0.1 (from https://github.com/passff/passff-host)

- How have you installed the host app? Two tests, same results:
  - curl -sSL https://github.com/passff/passff-host/releases/download/1.0.1/install_host_app.sh | bash -s -- firefox (user mode)
  - curl -sSL https://github.com/passff/passff-host/releases/download/1.0.1/install_host_app.sh | bash -s -- firefox (root mode)

- Your preferences
  - In the host app `passff.py`: 
    COMMAND      = "/usr/bin/pass"
    COMMAND_ARGS = []
    COMMAND_ENV  = {
        "TREE_CHARSET": "ISO-8859-1",
        "PATH": "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
    }
    CHARSET      = "UTF-8"

---

### Describe *objectively* your problem

I'm getting an error "Connection to the host app failed or returned an unexpected result" with "[14:27:44] ls -> Error: password store is empty... (1)" as details.

When I try to run from command line:

    echo -e "\x02\x00\x00\x00[]" | /usr/lib/mozilla/native-messaging-hosts/passff.py | tail -c +4; echo

It seems ok (I get some json looking like my pass structure), with `"version": "1.0.1"` at the end.

I had a look at other issues, but didn't find this exact error, did I miss something (in the issues or in my configuration) or does it look like a bug?

Thanks,

**Comment by 5bentz** [comment]
Hello,
I'm using Debian Testing, basically the same system as yours.

* Have you initialized a zx2c4 pass repository? PassFF requires it.
* Try `pass` in the commandline: do you see this output?
```
Error: password store is empty. Try "pass init".
```
It might be a PEBKAC :3

**Comment by tvo6** [comment]
'Lo,
Sure, I used pass for a long time now; and I get my github password (for example) with
`pass github/tvo6` (and it works).
So it may be a PEBKAC, but not this one ;)

**Comment by tvo6** [comment]
Indeed, this was the PEBKAC; once the PASSWORD_STORE_DIR, everything works…
Thanks, and apologies for this unnecessary issue.

**Comment by 5bentz** [comment]
;)
The documentation might be obscure.
* The README in passff does not talk about env variables
* The README in passff-doc mentions env variables at the very end.

However, the preferences of passff is pretty clear: *See passff.py for changing the environment variables of pass.*
