### ISSUE TITLE
Passff not comunicating with passff-host

### ISSUE THREAD

**Issue by marceloakira** [passff/passff-host#27]
### General information. Describe your environment

- Versions
  - Operating system: ubuntu 18.04.1
  - Browser: Firefox 61.0.1 (64-bit)
  - PassFF: PassFF 1.5.1
  - Host app: 1.0.2

- How have you installed the host app?

I executed this commands:
$ VERSION=1.0.2
$ curl -sSL https://github.com/passff/passff-host/releases/download/${VERSION}/install_host_app.sh | bash -s -- firefox

- Your preferences
  - In the host app `passff.py`: 

  "name": "passff",
  "description": "Host for communicating with zx2c4 pass",
  "path": "/home/akira/.mozilla/native-messaging-hosts/passff.py",
  "type": "stdio",
  "allowed_extensions": [ "passff@invicem.pro" ]
}

---

### Describe *objectively* your problem

Nothing is displayed at passff in firefox. But in command line, 'pass' is working normal. 

In status bar, I have this message:
[19:30:10] ls -> (0) no error message

I executed the command:
$ echo -e "\x02\x00\x00\x00[]" | ./passff.py | tail -c +4; echo

And the result is:
{"exitCode": 0, "stdout": "a}_gO#.0/&34MXr#\n", "stderr": "", "version": "1.0.2"}

There is a slightly difference, stdout result in a randomly generated password, the same of 'pass' command, which the version is 1.7.1. Does it should be a static message "Password Store\n"?

**Comment by 5bentz** [comment]
Hello Marceloakira,

Thanks for the thorough report :+1: 
```
stdout result in a randomly generated password, the same of 'pass' command, which the version is 1.7.1.
```
Are you saying that `pass` generates a password when called without any arguments?
What is the output of your `pass` command?

`passff.py` assumes that `pass` defaults to listing the files (ie. `pass list`).
I'll fix that.

**Comment by 5bentz** [comment]
Actually, passff.py runs `pass --`. And that `--` can be parsed as an extension.
If an extension with such a name (`--`) exists, pass runs the extension instead of listing the files.

If submitted a PR.

**Comment by 5bentz** [comment]
Let me know if the fix works for you ;)

**Comment by lanodan** [comment]
> ``passff.py`` **WRONGLY** assumes that pass defaults to listing the files (ie. ``pass list``).

Are you sure of that? The manpage (``pass(1)`` 1.7.3) explicitly says:
> If no COMMAND is specified, COMMAND defaults to either show or ls, depending on the type of specifier in ARGS. Alternatively, if PASSWORD_STORE_ENABLE_EXTENSIONS is set to "true", and the file .extensions/COMMAND.bash exists inside the password store and is executable, then it is sourced into the environment, passing any arguments and environment variables.

**Comment by lanodan** [comment]
Aah, I missed the ``--`` part when re-reading this bug, sorry.

**Comment by marceloakira** [comment]
> @lanodan says:
> Let me know if it works for you ;)
> I've just written that without testing it again. I hope I forgot nothing.

It not worked, but your feedback helped me a lot, since I've got some ideas to solve the problem. 

Read lines 360 to 363 of command 'pass' (https://git.zx2c4.com/password-store/tree/src/password-store.sh?h=1.7.1#n360):
...
        local path="$1"
	local passfile="$PREFIX/$path.gpg"
	check_sneaky_paths "$path"
	if [[ -f $passfile ]]; then
...

I've found a unused file at ~/.password-store/.gpg. I removed it and passff is functioning now. Now the results of commands 'pass' and 'pass ls' are the same. Thank you.

**Comment by 5bentz** [comment]
Oh ok, `pass` tries to open `"$path.gpg"` which expends to `.gpg`. This is a bummer.

The root cause was different, however the conclusion is the same: PassFF shouldn't trust `pass` or `pass --` outputs, which can be *hijacked* by a nasty `.gpg` file or by an extension named `--`.

Your case is scary, because once my pinentry program is done (I have typed my password for the decryption), Firefox (or even my computer) would **freeze** for a few seconds when I try to refresh the list of passwords in PassFF...while eating an entire CPU core.

Thanks to you for the report :100:

**Comment by 5bentz** [comment]
EDIT: Actually, `pass show` and `pass show --` are also hijacked by the file `.gpg`.

**Comment by nkruglikov** [comment]
Hi, today I encountered the same issue, which was resolved by deleting `.gpg` file. I suspect that this file was created by passff, while I was fooling around with freshly-installed extension.
