### ISSUE TITLE
Doc: Handling of the URL attribute

### ISSUE THREAD

**Issue by polcak** [passff/passff-host#30]
Hello,

I am using passff in firefox. My set up for pass is a hierarchy of folders with files (see https://www.passwordstore.org/ - Using the password store). Each file contains the password, username, URL and possibly more attributes (see https://www.passwordstore.org/ - Usernames, Passwords, PINs, Websites, Metadata, et cetera, ). However, I am not sure what should I have in the URL attribute.

Let's say I want to specify the URL for "https://bugs.gentoo.org/index.cgi?GoAheadAndLogIn=1". Do I insert the full URL? Should I insert ""https://bugs.gentoo.org/index.cgi", "https://bugs.gentoo.org", "https://bugs.gentoo.org/*" or even "gentoo.org"? I went for the option "https://bugs.gentoo.org" but I am not sure if other options are better or not.

Moreover, consider that I also have an account on "https://wiki.gentoo.org" or "https://forums.gentoo.org". Each account is specified in a separate file. When I try to access one of the account, passff shows me a pop up that contains all options on the gentoo domain. However, when I am on the URL "https://bugs.gentoo.org/index.cgi?GoAheadAndLogIn=1" I am expecting to see only the bugs account in the pop up and not forums, wiki, etc. What is even more strange I also see an account with URL https://bugs.python.org on the "https://bugs.gentoo.org/index.cgi?GoAheadAndLogIn=1" which is completely unexpected for me.

Please, can you explain more the attribute URL in the documentation/README. I am not sure how to use it, if my expectation of the attribute match yours and if the behaviour I am seeing is a bug or expected outcome.

I am using www-plugins/passff-host-1.0.2, app-admin/pass-1.7.3, PassFF 1.5.1, www-client/firefox-63.0 and python 3.6 interpret.

**Comment by tuxor1337** [comment]
Firstly: The behaviour you are seeing is expected. We can only match based on the names of the password store entries. Anything beyond that would require decrypting the whole password store. The url field inside the entries is used for the "Go to, fill and submit" functionality and (optionally) for phishing prevention.

Secondly: You are right that we should explain this logic in the documentation somewhere in more detail.

**Comment by 5bentz** [comment]
I have some free-time this week-end, I will look into that :+1: 
Thanks for the report.

The URL attribute in the file is indeed used for the _goto_ functionality of PassFF. Ie: Open the specified URL in the current tab.

**Comment by 5bentz** [comment]
@polcak I've updated the doc on my branch: https://github.com/5bentz/passff/tree/doc_special_fields#password-formats

**Comment by polcak** [comment]
@tuxor1337 Thank you for clarification on how the URL record works.

@5bentz Thank you for the text. However, it is only about the "Go to, fill and submit" functionality. However, I have some accounts that are valid for multiple services typically hosted on some domain. Am I expected to have multiple files, each with the same username/login but different URL? That is not practical when the password changes.

Also, my workflow is not based on the "Go to, fill and submit". Rather I visit the login URL manually, maybe from bookmarks, maybe through URL bar auto fill. On the log In page, I see a list of options where (I think but didn't look into code) each item (subdirectory or filename) partially matches the opened URL (log in page). It would be great to have the matching between the file structure and URL described and have a recommended layout for the password database.

For example, from my first post, how do I prevent the username/password stored as floss/python.org/bugs from appearing on the https://bugs.gentoo.org/index.cgi?GoAheadAndLogIn=1?

**Comment by polcak** [comment]
Looking at the code, I think I am looking for a documentation on how to structure my database for the code between https://github.com/passff/passff/blob/master/src/modules/pass.js#L92 and line 163.

**Comment by tuxor1337** [comment]
Please clarify the following:

* Do you want to prevent certain entries to show up (at all) when you are on certain web pages?
* Do you want certain entries to rank higher/lower on certain web pages?

So far, the only examples that you presented point to the first option. However, I don't see the usecase where it's desirable for some entries to be suppressed. For example: You say that floss/python.org/bugs appears when you are on bugs.gentoo.org. So what? Where is the problem?

**Comment by polcak** [comment]
@tuxor1337 I want to do both.

I see several security/privacy/usability problems with situations like floss/python.org/bugs appearing on bugs.gentoo.org.

* If I misclick and select inappropriate option, I reveal my credential from one service to another service.  
* For me, on one login page, 11 options are listed but only one of them belongs to the service which means I have to search for the correct entry. With only one option, there is much lower work for the brain and the login is procedure takes much less time.
* If I want to log in to a service and someone is looking at me, I may not want to know them the names of other services I have in my wallet.

Ideally for me, passff shows me only one option on each page which means that I save time and I focus on the login procedure instead of list searching.

**Comment by tuxor1337** [comment]
We could add an option to show only the first N matching entries and you would then set N=1. This would still expose non-related entries in cases where the matching logic doesn't produce the desired result. Is that what you intend?

**Comment by polcak** [comment]
@tuxor1337: Having the possibility to show only N options seems like a good idea.

Anyway, my biggest concern at the moment is how do I set up file names in my pass database - what names do I use to have the best user experience in pasff. AFAIK only the URL and the password file name are considered. As it stands now, I think, I need to run the code between https://github.com/passff/passff/blob/master/src/modules/pass.js#L92 and line 163 for my URLs and file names and learn the quality of the match, experiment and so on. So that I have the best match with the expected file for each URL. Is this what I (as a user of pasff) am expected to do? Is the code expected to change in the future?

**Comment by tuxor1337** [comment]
Generally speaking, the match quality is best, if the exact hostname as well as all alphanumeric parts of the URL path appear exactly in your entry's name. An entry is excluded from the matching if no part of the hostname is contained in its name. Matching hostname parts are more important than matching parts from the rest of the URL.

For the URL "https://bugs.gentoo.org/index.cgi?GoAheadAndLogIn=1", best match quality is reached if your password store entry contains the strings "bugs.gentoo.org", "index" and "GoAheadAndLogIn" in arbitrary order. 

I personally get the best results from naming the entries after the exact hostname because, in my password store, there is no example where I have multiple credentials for one hostname. For the above example, I would use the password entry "/some/arbitrary/path/bugs.gentoo.org" and this will always rank highest.

If you happen to have several credentials for one hostname I would name a directory after the hostname and list the different credentials inside that directory. So, if you have credentials for the URLs "https://my.example.com/cloud" and "https://my.example.com/blog" and "https://my.example.com/gitea", you could store them in your password store as "/some/path/my.example.com/cloud", "/some/path/my.example.com/blog" and "/some/path/my.example.com/gitea". But that's just one option. Having "/personal/my.example.com-cloud", "/business/my.example.com-blog" and "/dev/my.example.com-gitea" etc. will work equally well. It's up to you.

**Comment by polcak** [comment]
Thank you @tuxor1337, now my matching works much better and I have much better idea how the password searching works. I think that your today post should be a part of the docs.

**Comment by tuxor1337** [comment]
Fixed by passff/passff@8fc95df607df803e9a9a8339329ae6c2edc51367
