### ISSUE TITLE
how to configure host app for icecat?

### ISSUE THREAD

**Issue by Avizini** [passff/passff-host#31]
### General information. Describe your environment

- Versions
  - Operating system: Fedora
  - Browser: Icecat
  - PassFF: -
  - Host app: -

### Describe *objectively* your problem

```
bash: firefox: command not found...
bash: opera: command not found...
bash: vivaldi]: command not found...
bash: chromium: command not found...
Install package 'firefox' to provide command 'firefox'? [N/y] n
```

**Comment by tuxor1337** [comment]
What exactly is the problem? Have you tried following the instructions for firefox?

**Comment by Avizini** [comment]
When I run that it outputs this

```
/install_host_app.sh -s firefox
Usage: ./install_host_app.sh [OPTION] [chrome|chromium|firefox|opera|vivaldi]

  Options:
    -l, --local    Install files from disk instead of downloading them
    -h, --help     Show this message
```

**Comment by tuxor1337** [comment]
Yeah, in fact there is no `-s` option. Where did you find your commandline anyways? Which instructions do you actually follow?

**Comment by Avizini** [comment]
> Where did you find your commandline anyways?

I don't understand that.

Thanks, it is working now! & sorry if this was silly I am new to this

**Comment by tuxor1337** [comment]
I would like to know, which instructions you have been following when you posted this: https://github.com/passff/passff-host/issues/31#issuecomment-445445202

**Comment by Avizini** [comment]
`Usage: ./install_host_app.sh [OPTION] [chrome|chromium|firefox|opera|vivaldi]`

This was the output for `./install_host_app.sh`, I didn't understand that I have to replace that bracket thing with browser name so I kept it like that.

**Comment by tuxor1337** [comment]
But why `-s`?

**Comment by Avizini** [comment]
Because `./install_host_app.sh -l [chrome|chromium|firefox|opera|vivaldi]` & `./install_host_app.sh [chrome|chromium|firefox|opera|vivaldi]` was not working, revisited the repository for extension and saw `-s` over there and was trying with  `-s` to see if it works.

**Comment by tuxor1337** [comment]
Thanks, so I guess you mean this command line because that's the only place I found where a `-s` option is used in the docs:

    curl -sSL https://github.com/passff/passff-host/releases/download/${VERSION}/install_host_app.sh | bash -s -- firefox

**Comment by Avizini** [comment]
Yes I saw `-s` from there
