### ISSUE TITLE
Docs state Python 3.5, but Python 3.6 features are used

### ISSUE THREAD

**Issue by wastevensv** [passff/passff-host#39]
### General information. Describe your environment

- Versions
  - Operating system: Debian 9.8
  - Browser: 60.6.1esr
  - PassFF: 1.7.0
  - Host app: 1.2.0

- How have you installed the host app?
Bash script mentioned in README.

---

### Describe *objectively* your problem

I noticed the newest version of passff.py (1.2.0) uses formatting strings. These were introduced in Python 3.6 (see [PEP 498](https://www.python.org/dev/peps/pep-0498/)). However, the docs still list Python 3.5 as the minimum version. This should be instead be >=Python 3.6.

Also, Debian stable only has Python 3.5 for now. I'm upgrading to Debian testing soon, so that'll fix my problem. But it's worth noting in the docs somewhere.

**Comment by tuxor1337** [comment]
Alternatively, we could add a fix that restores Python 3.5 support by avoiding formatting strings. It only affects a single line...
