### ISSUE TITLE
passff add-on got deactivated caused by missing signing for firefox

### ISSUE THREAD

**Issue by kreutpet** [passff/passff-host#42]
### General information. Describe your environment
- Versions
  - Operating system: Ubuntu 19.04
  - Browser: 66.0.3 (64-Bit)
  - PassFF: 1.7.0 
  - Host app: ??

- How have you installed the host app?
app has worked before and was installed according guideline in github

- Your preferences
  - In the host app `passff.py`: 

command     = "/usr/bin/pass"
commandArgs = []
commandEnv  = {
    "TREE_CHARSET": "ISO-8859-1",
    # Default PATH for MacOS:
    #"PATH": "/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin",
}
charset     = "UTF-8"
---

### Describe *objectively* your problem
After startup of firefox the add-on is missing and shows a warning that it has been deactivated because of missing add-on signing. See here the link the error message references
https://support.mozilla.org/en-US/kb/add-on-signing-in-firefox
Application has work before , somehow i guess it came with the Firefox update.
I really like the add-on and it worked now for very long time
Not sure if i should create this issue in the other passff repository, please comment

**Comment by tuxor1337** [comment]
This is an upstream issue, see https://github.com/passff/passff/issues/404 and https://bugzilla.mozilla.org/show_bug.cgi?id=1548973

**Comment by 5bentz** [comment]
> A formal post-mortem [will be released] next week

* [Technical Details on the Recent Firefox Add-on Outage](https://hacks.mozilla.org/2019/05/technical-details-on-the-recent-firefox-add-on-outage/)
