### ISSUE TITLE
Security?

### ISSUE THREAD

**Issue by bbc2** [passff/passff-host#46]
There's no mention of how the security of the host application is achieved. For instance, what prevents other browser extensions from accessing my passwords?

I'm a new user and so far happy with the features provided by passff but also concerned about its security.

**Comment by tuxor1337** [comment]
Whenever you install an extension to Firefox, it's able to see every password you insert into any login form. So, from that point of view, there's nothing PassFF could do to protect you.

However, the passff host app itself can only be executed by the original PassFF extension. This is hardcoded in the file `passff.json`. No other Firefox extension can execute the pass command without your permission.

**Comment by bbc2** [comment]
Those are good points and I can indeed see that all my extensions have the "Access your data for all websites" permission.  Also, the approach you described seems sensible to me.

Thank you for the clarification!
