### ISSUE TITLE
Easier command for getting latest install script

### ISSUE THREAD

**Issue by xerus2000** [passff/passff-host#49]
Using the GitHub API, one can easily get the latest script, that way you don't have to manually adjust the `VERSION` variable ;)
```sh
curl -s https://api.github.com/repos/passff/passff-host/releases/latest | grep -o "http.*install_host_app.sh" | xargs curl -sSL
```
Maybe adjust the README?

**Comment by tuxor1337** [comment]
Thanks for the hint. It's even easier than that: https://help.github.com/en/github/administering-a-repository/linking-to-releases

**Comment by xerus2000** [comment]
oh wow, that's nice :smile: yeah the script above can also be used for releases with changing names (e.g. if it contains the version), that's why I simply adapted that at first
