### ISSUE TITLE
Location of pass incorrect in passff.py

### ISSUE THREAD

**Issue by notklaatu** [passff/passff-host#50]
### General information. Describe your environment

- Versions
  - Operating system: RHEL 8
  - Browser: Firefox 81.0.2 (64-bit)
  - PassFF: 1.2.1
  - Host app: 1.7.3

- How have you installed the host app?

---

### Describe *objectively* your problem

I used the `install_host_app.sh` to install. In the passff.py script that was installed to my system, the location the `COMMAND` variable was set to `/usr/local/bin/pass` but the pass executable on my system is actually located in `/usr/bin/`. I assume this path got set by the installer(?)

Correcting the path enables passff-host to function as expected.

**Comment by tuxor1337** [comment]
What's the output of `install_host_app.sh` and which parameters did you pass on the command line?

**Comment by notklaatu** [comment]
I executed it this way: 

```
sh ./install_host_app.sh firefox
```

I no longer have the output of the initial install, and now I'm unable to replicate. I'll close this for now and if it happens again, I'll paste in relevant info.
