### ISSUE TITLE
Is it possible for this to work if Python3 is not the default version?

### ISSUE THREAD

**Issue by mlncn** [passff/passff-host#52]
`curl -sSL github.com/passff/passff-host/releases/latest/download/install_host_app.sh | bash -s -- firefox` resulted in:
```
Python 3 executable located at /home/linuxbrew/.linuxbrew/bin/python3
```
or does this mean it worked?  How to test?  `passff-host` gives "command not found".

This is what i have locally:

```bash
$ python --version
Python 2.7.18
$ python3 --version
Python 3.9.2
```

**Comment by tuxor1337** [comment]
The output about Python 3 is fine. If you want to test that everything went fine, you need to find out where the `passff.py` script is located. This information is written in the [README](https://github.com/passff/passff-host#latest-from-github). After that, you can check the output of the script following the instructions in the [README](https://github.com/passff/passff-host#check-the-output-of-the-host-app).
