### ISSUE TITLE
OS X: sed complains about invalid code

### ISSUE THREAD

**Issue by linusr** [passff/passff-host#6]
Fails with below error,

    11:56:04 $make
    cp ./install_host_app.sh ../bin/testing/install_host_app.sh
    sed -i "s/_VERSIONHOLDER_/testing/g" ../bin/testing/install_host_app.sh
    sed: 1: "../bin/testing/install_ ...": invalid command code .
    make: *** [../bin/testing/install_host_app.sh] Error 1

**Comment by vizv** [comment]
Related to https://github.com/passff/passff-host/blob/1feab77c59bab91451242dba0fa3f1e6cf95e8f9/src/Makefile#L29 same sed problem as #5
