### ISSUE TITLE
[MacOS] Non standard characters stop searching password store

### ISSUE THREAD

**Issue by mflis** [passff/passff-host#75]
### General information. Describe your environment
My `.password-store` has few dozens entries and file names of some of them contain non-ascii characters(polish in my case, e.g. ą,ę)
I use the same store on both Linux(Arch) and Mac OS. On Linux everything works fine. I noticed that on Mac entry search seems to be stopped  by these non-ascii characters.

- Versions
  - Operating system: macOS High Sierra  10.13.6
  - Browser: Mozilla firefox 63.0 (64 bits)
  - PassFF: 1.5.1 
  - Host app: passff-host 1.0.2

Status line output: `[08:47:57] ls -> (0) no error message`

Sometimes I get also this output, but I wasn't able to reproduce it in minimal example:
 `[08:44:16] ls -> (0) sed: RE error: illegal byte sequence `

### Actual behaviour
Entries that are listed after file with non-ascii characters (in order as listed in `tree` command) are not included in toolbar menu.

### Expected behaviour
All entries with file name that matches domain name should be listed in toolbar menu

### Steps to reproduce the behaviour
1. Configure empty password store together with passff
2. Create entries  in password store
```
touch gitlab.com.gpg
touch kę.gpg
touch twitter.com.gpg
```
3. Refresh pass-ff
4. Go to gitlab.com and invoke pass-ff toolbar menu. Entry will  be listed.
4. Go to twitter.com and invoke pass-ff toolbar menu. Entry will not  be listed.

**Comment by tuxor1337** [comment]
Closing as duplicate of #25
