### ISSUE TITLE
Connection to the host app failed or returned an unexpected result!

### ISSUE THREAD

**Issue by khinsen** [passff/passff-host#9]
macOS 10.12, Firefox 59.2, PassFF 1.3b, pass installed via homebrew, works fine from the terminal
PATH, COMMAND defined in passff.py look OK

When I start Firefox and click on the PassFF icon, I get the error message
```
Connection to the host app failed or returned an unexpected result!

Make sure you have the latest version of the PassFF host app installed by following the installation instructions on GitHub.
```

How do I go about debugging this? Is the "unexpected result" stored somewhere? Can I intercept communication between Firefox and the host app? Anything else I can do?

**Comment by tuxor1337** [comment]
Which verison of the host app do you use?

**Comment by khinsen** [comment]
I can't find a version number anywhere. I cloned the GitHub repository a few hours ago, so I guess it's the most current version.

**Comment by tuxor1337** [comment]
What's the value of VERSION in the passff.py you're using?

How did you install the host app? The README tells you to do this if you want to install the latest version from the source:

    $ cd ./src
    $ make
    $ cd ../bin/testing
    $ ./install_host_app.sh --local [firefox|chrome|opera|chromium|vivaldi]

**Comment by khinsen** [comment]
`VERSION = "_VERSIONHOLDER_"`

**Comment by khinsen** [comment]
Oops... Just redid the installation. There was an error during `make` that I had overlooked:
```
src/ $ make                                                          [19:16:31]
mkdir -p ../bin/testing
cp ./install_host_app.bat ../bin/testing/install_host_app.bat
sed -i "s/_VERSIONHOLDER_/testing/g" ../bin/testing/install_host_app.bat
sed: 1: "../bin/testing/install_ ...": invalid command code .
make: *** [../bin/testing/install_host_app.bat] Error 1
```

**Comment by khinsen** [comment]
Looks like I am in the same situation as #6 then!
